# ==============================================================================
# Script: 00_setup_and_bootstrap.R
# Author: COSMOS Polypharmacy Research Team
# ==============================================================================

# 1. Required Packages
# ------------------------------------------------------------------------------
libraries <- c(
  "dplyr", "tableone", "skimr", "tidyverse", "lubridate", "haven", 
  "ggplot2", "naniar", "devtools", "reader", "missForest", "psych", "survival",
  "purrr", "rmarkdown", "knitr", "markdown", "stringr", "ggsurvfit", "labelled",
  "survminer", "Matrix", "lme4", "afex", "riskRegression", "pammtools",
  "adjustedCurves", "readxl", "boot", "survey", "nnet", "mice", "lmtest", "sandwich", "scales"
)

# Suppress package startup messages for cleaner execution
invisible(lapply(libraries, function(pkg) suppressPackageStartupMessages(require(pkg, character.only = TRUE))))


# --- BOOTSTRAP FUNCTIONS ALGORITHM ---

# ==============================================================================
# ==============================================================================

library(dplyr)
library(data.table)
library(foreach)
library(doParallel)

#' Run MSM Cluster-Level Bootstrap for Cumulative Incidence Ratios
#' @param data IPW-weighted longitudinal dataframe with stabw_t and interaction terms predefined
#' @param formula_str String of the outcome formula (e.g., "death_event ~ polypharmacy_med + visit + ...")
#' @param B Number of bootstrap replications (default 500)
#' @param weight_func Function to compute IPW weights for each bootstrap sample (default compute_msm_weights_exact)
#' @param weight_col String for the weight column name generated by weight_func (default "stabw_t")
run_msm_bootstrap_CIR <- function(data, formula_str, weight_func = compute_msm_weights_exact, weight_col = "stabw_t", B = 500) {
  set.seed(123)
  ids <- unique(data$id)
  n_id <- length(ids)
  
  cat(sprintf("Initiating %d cluster-level bootstrap iterations...\n", B))
  
  boot_ids <- matrix(sample(ids, n_id * B, replace = TRUE), nrow = n_id, ncol = B)
  
  ncore <- max(1, parallel::detectCores() - 1)
  cl <- makeCluster(ncore)
  registerDoParallel(cl)
  

  
  boot_mat <- foreach(b = seq_len(B), .combine = rbind, .packages = c("dplyr", "data.table")) %dopar% {
    
    # Extract sampled IDs for this bootstrap iteration
    sampled_ids <- boot_ids[, b]
    
    # Expand dataset physically assigning unique IDs for replicates to ensure valid grouping (e.g., cumprod)
    df_b_list <- lapply(seq_along(sampled_ids), function(i) {
      subj_data <- data[data$id == sampled_ids[i], ]
      subj_data$orig_id <- subj_data$id
      subj_data$id <- paste0("boot_", i) # Override with unique ID
      return(subj_data)
    })
    df_b <- bind_rows(df_b_list)
    
    # Re-evaluate weighting model on the bootstrap sample using the provided weighting function
    df_b <- weight_func(df_b)
    
    # Fit weighted pooled logistic model
    # Use the specified weight column generated by weight_func
    w_vec <- df_b[[weight_col]]
    if (is.null(w_vec)) stop(paste("Weight column", weight_col, "not found after running weight_func."))
    
    fit <- glm(as.formula(formula_str), data = df_b, weights = w_vec, family = quasibinomial())
    
    # Prepare Prediction Grid baseline
    base <- df_b %>% filter(visit == 0)
    n <- nrow(base)
    reps <- 0:4
    newdat <- base[rep(seq_len(n), each = length(reps)), ]
    newdat$visit <- rep(reps, times = n)
    newdat$visit2 <- newdat$visit^2
    
    # Scenario A: Sustained Polypharmacy
    poly1 <- newdat
    poly1$polypharmacy_med <- 1
    p1 <- predict(fit, newdata = poly1, type = "response")
    poly1$s <- ave(1 - p1, poly1$id, FUN = cumprod)
    
    # Scenario B: Sustained No-polypharmacy
    poly0 <- poly1
    poly0$polypharmacy_med <- 0
    p0 <- predict(fit, newdata = poly0, type = "response")
    poly0$s <- ave(1 - p0, poly0$id, FUN = cumprod)
    
    # Extrapolate CIR vector for visits 1-4
    sapply(1:4, function(v) {
      S1 <- mean(poly1$s[poly1$visit == v])
      S0 <- mean(poly0$s[poly0$visit == v])
      (1 - S1) / (1 - S0)
    })
  }
  
  stopCluster(cl)
  
  # Derive Exact 95% Confidence Intervals
  CIR_point_boot <- apply(boot_mat, 2, mean, na.rm = TRUE)
  
  CI_tbl <- data.frame(
    visit = 1:4,
    CIR   = CIR_point_boot,
    lower = apply(boot_mat, 2, quantile, 0.025, na.rm = TRUE, type = 6),
    upper = apply(boot_mat, 2, quantile, 0.975, na.rm = TRUE, type = 6)
  ) %>% mutate(across(c(CIR, lower, upper), ~ round(.x, 2)))
  
  return(CI_tbl)
}
